name: MOBChatBot
version: 0.2.0
main: me.drendov.MOBChatBot.MOBChatBot
api-version: 1.21
author: drendov
description: AI-powered chat bot for private Minecraft servers

commands:
  mobchat:
    description: Main command for MOBChatBot
    usage: /mobchat <message>
    aliases: [mc, chatbot]
  mobchatreload:
    description: Reload the plugin configuration
    usage: /mobchatreload
    permission: mobchatbot.admin

permissions:
  mobchatbot.use:
    description: Allows players to chat with the AI bot
    default: true
  mobchatbot.admin:
    description: Grants admin permissions to manage the plugin
    default: op